### ISSUE TITLE
Do not drop database until database file will be available

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/scripthor#1]
This script remove the database before check that the environment is available, so if you do not have access for any reason your local database dissapear.

Consider to check that the environment or the file is available before drop the local database.

**Comment by rsanzante** [comment]
I think it would be better to make a backup prior to trying to load a database. The local dump is corrupted or you lost connection after checking access to the remote environment you may end not the same situation: no local database loaded and no valid local database dump. However, if a flag triggers a backup before dumping the local database you can always reload that backup.

**Comment by Eduardo-Morales-Alberti** [comment]
The benefit is not worth it, the dump and the reloading database will be slower than retrying the process again.
