### ISSUE TITLE
Frontend build step should be skip if THEME_PATH is not declared during reload-local

### ISSUE THREAD

**Issue by Esrohym** [Metadrop/scripthor#23]
It may exists a wide incompatibility with the themes in certain projects making impossible to complete reload local because frontend build is a required step.

## Proposed Solution

Skip frontend build step if THEME_PATH is not declared in .env file or if it is empty.

## MR

https://github.com/Metadrop/scripthor/pull/24/files

**Comment by jorgetutor** [comment]
love it!
