### ISSUE TITLE
Add the option to ask before commit on update script

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/scripthor#30]
When the update script is executed on local, we should review the commit for each update before it is committed because that way we can avoid some not wanted changes like wrong configuration or dependecies. After all the script is finished, is more complicated to revert or fix a previous commit without polluting the history.

I would add it only as an option, not something required.

**Comment by Eduardo-Morales-Alberti** [comment]
Git can revert commits. Not worth it.

**Comment by omarlopesino** [comment]
Let's reopen this issue in the case of reverting the composer.lock commits becomes problematic, as sometimes reverting composer.lock changes leads to conflicts.
