### ISSUE TITLE
Remove locale from reload local script

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [Metadrop/scripthor#39]
The reload local script should only reload the environment with a remote environment, but never download or overwrite the translations or configuration from other sources, that's why we should remove locale steps.

**Comment by omarlopesino** [comment]
It looks reasonable argument but I think it is important to discuss it so we don't want to have this back in our projects.

What is the reason to remove this option, knowing that there is an argument to skip translations? Have you had a problem in your project that made you decide this action is not necessary, even having the possibility to skip the step?
