### ISSUE TITLE
update-helper.sh script does not work properly without author parameter

### ISSUE THREAD

**Issue by albefer** [Metadrop/scripthor#45]
When ./update-helper.sh is launched the updates and configuration are not commited, it only launch "git add". We need to save every change in modules in separate commits, and it is necessary to add the parameter author for this functionality to work.

Approach: Add a warning or error message when launching update-helper.sh without the author parameter, or launch an error message and prevent it from being executed.

**Comment by omarlopesino** [comment]
Between the two solutions proposed by albefer I'd prefer to display an error. The expected result of the script to generate a commit for each update/consolidation done. So the script must not start updating without that parameter

I propose , before doing anything in the script, checking that the author is not empty. In that case, display an error to the user.

**Comment by omarlopesino** [comment]
Deprecated issue because the command has been moved to metadrop/drupal-updater. Now the author has default value, so the problem is solved in drupal-updater.
